---
language: python
python: "2.7"

# Travis uses old distros...
dist: trusty

# Use the new container infrastructure
sudo: required

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version


script:
  # Basic role syntax check
  - ansible-playbook hardening.yml -i inventory --syntax-check

