---
- name: systemd system.conf
  become: 'yes'
  become_method: sudo
  template:
    src: etc/systemd/system.conf.j2
    dest: /etc/systemd/system.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  notify:
    - systemctl daemon-reload
  tags:
    - systemd
    - system.conf
    - security

- name: systemd user.conf
  become: 'yes'
  become_method: sudo
  template:
    src: etc/systemd/user.conf.j2
    dest: /etc/systemd/user.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  notify:
    - systemctl daemon-reload
  tags:
    - systemd
    - user.conf
    - security
...
