---
- name: systemd logind
  become: 'yes'
  become_method: sudo
  template:
    src: etc/systemd/logind.conf.j2
    dest: /etc/systemd/logind.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  notify:
    - systemctl daemon-reload
  tags:
    - systemd
    - logind
    - security
...
