---
- name: resolved.conf
  become: 'yes'
  become_method: sudo
  template:
    src: etc/systemd/resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  notify:
    - systemctl daemon-reload
  tags:
    - resolved.conf
    - security
...
